server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      routes:
        # Rutas para Customer Service
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/clientes/**, /api/personas/**
          filters:
            - StripPrefix=0
        
        # Rutas para Account Service
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/cuentas/**, /api/movimientos/**
          filters:
            - StripPrefix=0
        
        # Ruta para reportes (manejada por el gateway)
        - id: reports-service
          uri: lb://api-gateway
          predicates:
            - Path=/api/reportes/**
          filters:
            - StripPrefix=0

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Logging
logging:
  level:
    com.sofka.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
