server:
  port: 0

spring:
  application:
    name: customer-service-test
  
  datasource:
    url: jdbc:mysql://localhost:3306/customer_test_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Wire2681
  
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    defer-datasource-initialization: true
  
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

# Eureka Client Configuration (disabled for tests)
eureka:
  client:
    enabled: false

# Logging
logging:
  level:
    com.sofka.customer: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
